# Generated by Django 5.1.2 on 2024-10-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(default='healthy', max_length=200),
        ),
    ]
