# Generated by Django 5.1.5 on 2025-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='behaviour',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
