# Generated by Django 5.1.5 on 2025-01-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('animals', '0004_animal_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalactivity',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.AlterUniqueTogether(
            name='animalactivity',
            unique_together={('animal', 'activity')},
        ),
    ]
