# Generated by Django 5.1.5 on 2025-02-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_animalactivity_counter'),
        ('animals', '0005_animal_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_day_1', models.IntegerField(default=0)),
                ('sitting_day_2', models.IntegerField(default=0)),
                ('sitting_day_3', models.IntegerField(default=0)),
                ('standing_day_1', models.IntegerField(default=0)),
                ('standing_day_2', models.IntegerField(default=0)),
                ('standing_day_3', models.IntegerField(default=0)),
                ('walking_day_1', models.IntegerField(default=0)),
                ('walking_day_2', models.IntegerField(default=0)),
                ('walking_day_3', models.IntegerField(default=0)),
                ('grazing_day_1', models.IntegerField(default=0)),
                ('grazing_day_2', models.IntegerField(default=0)),
                ('grazing_day_3', models.IntegerField(default=0)),
                ('ruminating_day_1', models.IntegerField(default=0)),
                ('ruminating_day_2', models.IntegerField(default=0)),
                ('ruminating_day_3', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
