# Generated by Django 5.1.5 on 2025-02-04 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitydurations'),
        ('animals', '0005_animal_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('recorded_value', models.IntegerField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
